// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	FindProductById(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) error
}

var _ Querier = (*Queries)(nil)
